version: "3.10"
services:
  worker:
    build: .
    environment:
      API_HASH: $API_HASH
      API_ID: $API_ID
      BOT_OWNER: $BOT_OWNER
      BOT_TOKEN: $BOT_TOKEN
      BOT_USERNAME: $BOT_USERNAME
      DATABASE_URL: $DATABASE_URL
      DB_CHANNEL: $DB_CHANNEL
      LOG_CHANNEL: $LOG_CHANNEL
      UPDATES_CHANNEL: $UPDATES_CHANNEL
